spring:
  application:
    name: match-logger
  datasource:
    url: jdbc:postgresql://localhost:5432/matchlogger
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

server:
  port: 8080
